name: new_gee_python
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ca-certificates=2023.05.30
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.9
  - pip=23.1.2
  - python=3.9.16
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - affine==2.4.0
    - appnope==0.1.3
    - asttokens==2.2.1
    - attrs==23.1.0
    - backcall==0.2.0
    - bqplot==0.12.39
    - branca==0.6.0
    - cachetools==5.3.1
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - colour==0.1.5
    - comm==0.1.3
    - contourpy==1.1.0
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - dill==0.3.7
    - earthengine-api==0.1.357
    - eerepr==0.0.4
    - et-xmlfile==1.1.0
    - executing==1.2.0
    - fastjsonschema==2.18.0
    - folium==0.14.0
    - fonttools==4.40.0
    - future==0.18.3
    - geemap==0.24.3
    - geocoder==1.38.1
    - google-api-core==2.11.1
    - google-api-python-client==2.90.0
    - google-auth==2.21.0
    - google-auth-httplib2==0.1.0
    - google-cloud-core==2.3.2
    - google-cloud-storage==2.10.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.5.0
    - googleapis-common-protos==1.59.1
    - httplib2==0.22.0
    - idna==3.4
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - ipyevents==2.0.1
    - ipyfilechooser==0.6.0
    - ipykernel==6.23.3
    - ipyleaflet==0.17.3
    - ipython==8.14.0
    - ipytree==0.2.2
    - ipywidgets==8.0.6
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.3.2
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.3.0
    - jupyter-core==5.3.1
    - jupyterlab-widgets==3.0.7
    - kaleido==0.2.1
    - kiwisolver==1.4.4
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - multiprocess==0.70.15
    - nbformat==5.9.2
    - nest-asyncio==1.5.6
    - numpy==1.25.0
    - openpyxl==3.1.2
    - packaging==23.1
    - pandas==1.5.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - platformdirs==3.8.0
    - plotly==5.15.0
    - prompt-toolkit==3.0.38
    - protobuf==4.23.3
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pygments==2.15.1
    - pyparsing==3.1.0
    - pyperclip==1.8.2
    - pyshp==2.3.1
    - python-box==7.0.1
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyzmq==25.1.0
    - rasterio==1.3.8
    - ratelim==0.1.6
    - referencing==0.30.2
    - requests==2.31.0
    - rpds-py==0.10.0
    - rsa==4.9
    - scikit-learn==1.3.1
    - scipy==1.11.3
    - scooby==0.7.2
    - seglearn==1.2.5
    - six==1.16.0
    - snuggs==1.4.7
    - stack-data==0.6.2
    - tenacity==8.2.2
    - threadpoolctl==3.2.0
    - tornado==6.3.2
    - tqdm==4.66.1
    - traitlets==5.9.0
    - traittypes==0.2.1
    - tsflex==0.3.0
    - typing-extensions==4.7.0
    - tzdata==2023.3
    - uritemplate==4.1.1
    - urllib3==1.26.16
    - wcwidth==0.2.6
    - widgetsnbextension==4.0.7
    - xyzservices==2023.5.0
    - zipp==3.15.0
# prefix: /Users/alexanderstudt/opt/anaconda3/envs/new_gee
